package com.metrix.architecture.metadata;

/**
 * Is an interace used for any class which can be used to generate <code>JSON</code> messages to be synced
 * with the back-end system. This includes MetrixUpdateMessage, MetrixBatchMessage and MetrixPerformMessage.
 * 
 * @since 5.5
 */
public interface IMetrixMessage {
	/**
	 * Formats the <code>JSON</code> document based on the data contained in the implementing 
	 * class's attributes.
	 * @return A formatted <code>JSON</code> document representing the data
	 */
	String format();
	/**
	 * Saves the <code>JSON</code> document generated by the format method to the sync tables.
	 * @return
	 */
    Boolean save();
}
